### ISSUE TITLE
Cannot install nodeserver, mismatch between python versions

### ISSUE THREAD

**Issue by neromir** [jimboca/udi-poly-Camect#9]
(Note, this is a duplicate of the following post on the UDI forum; found the request to post here afterward: https://forum.universal-devices.com/topic/32031-trouble-installing/)

I'm running polyglot on a Raspberry Pi and am unable to install the Camect nodeserver due to a mismatch between python versions. The image is a fresh Raspberry Pi OS image just downloaded today, fresh install of Polyglot as well.

The issue is that [install.sh](https://github.com/jimboca/udi-poly-Camect/blob/main/install.sh#L2) runs `pip install -r requirements.txt --upgrade --user`, which according to the environment on the RPi is Python 2.7.16. It looks like camect-py is only available in the Python 3 pip repository.

I need some assistance on knowing to to reconcile that. Does `/usr/bin/env Python` resolve to Python 3 on Polisy? If that's the case, I may be able to work around it.

**Comment by jimboca** [comment]
I will try to get this fixed tomorrow.

**Comment by jimboca** [comment]
Just released 0.2.2 which should fix the issue, it will be in the store within the hour.
